---
title: "Data Cleaning and Standards Assignment"
output: html_document
date: "2025-09-03"
autor: "Sandra Jaskowiak"
---
### Set Up -------------------------------------------------------------------

Install Packages that may be needed
```{r}
install.packages("tidyverse")
install.packages("palmerpenguins")
install.packages("assertr")
install.packages("lubridate")
install.packages("stringdist")
install.packages("GGally")
install.packages("sf")
install.packages("taxize")

library(readr)
library(tidyverse)
library(palmerpenguins)
library(assertr)
library(lubridate)
library(stringdist)
library(GGally)
library(sf)
library(taxize)
```

Set up working directory and import files
```{r}
# Set working directory
setwd("~/Simon Fraser University/Classes/Scientific Data Management for Ecology and Evolution/CIEE_Scientific-Data-Management")

#Import data files

######Template if only importing one file: my_data <- read.csv("your_file.csv") 

bromeliads_messy <- read_csv("BWG_database_messy/bwgv1_bromeliads_messy.csv")


```

Explore the data
```{r}
dim(bromeliads_messy) # [1] 76 rows (observations) and 18 columns (variables)
head(bromeliads_messy, 10) # view the first 10 rows of data
str(bromeliads_messy) # check the structure of the dataset
summary(bromeliads_messy) # summarize the dataset


